# Generated by Django 4.2.3 on 2023-07-15 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_but1_user_but2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='user',
            name='lastTime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
